services:
  postgres:
    container_name: surl-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: surl-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"


  backend:
    container_name: surl-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
