env: development

# server
host: localhost
port: 8080

# database
db_host: localhost
db_port: 5433
db_user: postgres
db_password: 0
db_name: avito_backend_assignment

# redis
redis_host: redis
redis_port: 6379
redis_password: ~
redis_expires: 5

# jwt
jwt_secret_key: secret
jwt_issuer: bai
jwt_access_token_expires_in: 5
jwt_refresh_token_expires_in: 10


