env: development

# server
host: localhost
port: 8080

# database
db_host: postgres
db_port: 5432
db_user: postgres
db_password: password
db_name: avito-backend-assignment

# redis
redis_host: redis
redis_port: 6379
redis_password: ~
redis_expires: 5

# jwt
jwt_secret_key: secret
jwt_issuer: bai
jwt_access_token_expires_in: 5
jwt_refresh_token_expires_in: 10


